name: Build bilingual RSS (multi)

on:
  workflow_dispatch:
  schedule:
    # 避开整点：GitHub 官方也说明高负载时 schedule 可能延迟，甚至队列任务可能被丢
    - cron: "7,37 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feeds
        env:
          AI_BASE_URL: ${{ secrets.AI_BASE_URL }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_MODEL: ${{ secrets.AI_MODEL }}
          FEED_URLS: ${{ secrets.FEED_URLS }}
          RSSHUB_BASE_URL: ${{ secrets.RSSHUB_BASE_URL }}
          MAX_NEW_ITEMS_PER_FEED: "6"
          MAX_TOTAL_NEW_ITEMS: "40"
        run: |
          python scripts/translate_multi.py

      - name: Commit updated output
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"
          git add public data
          git commit -m "Update bilingual feeds" || echo "No changes"
          git push

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4
